// Test generated by RoostGPT for test int-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace YourNamespace
{
    // Test suite for RegisterAction method
    [TestFixture]
    public class RegisterActionTests
    {
        // Test case for registering an action successfully
        [Test]
        public void Test_RegisterAction_Success()
        {
            // Arrange
            RegisterAction registerAction = new RegisterAction();
            string name = "Action1";
            bool actionExecuted = false;
            Action action = () => { actionExecuted = true; };

            // Act
            registerAction.RegisterAction(name, action);

            // Assert
            Assert.IsTrue(registerAction.Actions.ContainsKey(name));
            Assert.AreEqual(action, registerAction.Actions[name]);
        }

        // Test case for throwing NullReferenceException when actions is null
        [Test]
        public void Test_RegisterAction_NullReferenceException()
        {
            // Arrange
            RegisterAction registerAction = new RegisterAction();
            string name = "Action2";
            Action action = () => { /* do something */ };

            // Act and Assert
            Assert.Throws<NullReferenceException>(() => registerAction.RegisterAction(name, action));
        }
    }

    // Class containing RegisterAction method
    public class RegisterAction
    {
        public Dictionary<string, Action> Actions { get; set; } = new Dictionary<string, Action>();

        internal void RegisterAction(string name, Action action)
        {
            if (Actions is null)
            {
                throw new NullReferenceException();
            }

             Actions[name] = action;
        }
    }
}
