// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Windows.UI;

namespace MyProject.Tests
{
    [TestClass]
    public class ColorConverterTests
    {
        [TestMethod]
        public void TestToHtmlHex_WithValidColor_ReturnsCorrectHexCode()
        {
            // Arrange
            Color color = new Color { R = 255, G = 0, B = 0, A = 255 };
            
            // Act
            string result = ColorConverter.ToHtmlHex(color);
            
            // Assert
            Assert.AreEqual("#FF0000FF", result);
        }
        
        [TestMethod]
        public void TestToHtmlHex_WithInvalidColor_ReturnsEmptyString()
        {
            // Arrange
            Color color = new Color { R = 256, G = 0, B = 0, A = 255 };
            
            // Act
            string result = ColorConverter.ToHtmlHex(color);
            
            // Assert
            Assert.AreEqual(string.Empty, result);
        }
        
        [TestMethod]
        public void TestToHtmlHex_WithNullColor_ReturnsEmptyString()
        {
            // Arrange
            Color color = null;
            
            // Act
            string result = ColorConverter.ToHtmlHex(color);
            
            // Assert
            Assert.AreEqual(string.Empty, result);
        }
    }
}
