// Test generated by RoostGPT for test int-test using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;
using DevToys.Shared.Core;
using DevToys.Messages;

namespace NUnitTestProject
{
    [TestFixture]
    public class TestOpenToolInNewWindowMessage
    {
        [Test]
        public void TestOpenToolInNewWindowMessage_OpenToolInNewWindowMessage_d219e4444d()
        {
            // Arrange
            ToolProviderMetadata metadata = new ToolProviderMetadata();

            // Act
            OpenToolInNewWindowMessage message = new OpenToolInNewWindowMessage(metadata);

            // Assert
            Assert.IsNotNull(message);
            Assert.AreEqual(metadata, message.ToolProviderMetadata);
        }

        [Test]
        public void TestOpenToolInNewWindowMessage_OpenToolInNewWindowMessage_NullMetadata()
        {
            // Arrange
            ToolProviderMetadata metadata = null;

            // Act
            OpenToolInNewWindowMessage message = null;
            try
            {
                message = new OpenToolInNewWindowMessage(metadata);
            }
            catch (System.ArgumentNullException)
            {
                // ignore ArgumentNullException
            }

            // Assert
            Assert.IsNull(message);
        }
    }
}
