// Test generated by RoostGPT for test int-test using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevToys.Messages;
using NUnit.Framework;

namespace ChangeInfoBarStatusMessageTest
{
    [TestFixture]
    public class ChangeInfoBarStatusMessageTest
    {
        [Test]
        public void TestChangeInfoBarStatusMessage_ChangeInfoBarStatusMessage_cd114a1eec()
        {
            //Arrange
            bool isOpen = true;
            string message = "Test message";

            //Act
            ChangeInfoBarStatusMessage changeInfo = new ChangeInfoBarStatusMessage(isOpen, message);

            //Assert
            Assert.AreEqual(isOpen, changeInfo.IsOpen);
            Assert.AreEqual(message, changeInfo.Message);
        }

        [Test]
        public void TestChangeInfoBarStatusMessage_ChangeInfoBarStatusMessage_InvalidMessage()
        {
            //Arrange
            bool isOpen = true;
            string message = "";

            //Act & Assert
            Assert.Throws<ArgumentException>(() => new ChangeInfoBarStatusMessage(isOpen, message));
        }
    }
}
