// Test generated by RoostGPT for test int-test using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;
using DevToys.Shared.Core;
using DevToys.Messages;

namespace DevToys.Tests
{
    [TestFixture]
    public class ChangeSelectedMenuItemMessageTests
    {
        [Test]
        public void TestChangeSelectedMenuItemMessage_ChangeSelectedMenuItemMessage_21f3b66d7c()
        {
            //Arrange
            IToolProvider toolProvider = new ToolProvider();

            //Act
            ChangeSelectedMenuItemMessage changeSelectedMenuItemMessage = new ChangeSelectedMenuItemMessage(toolProvider);

            //Assert
            Assert.IsNotNull(changeSelectedMenuItemMessage);
            Assert.AreEqual(toolProvider, changeSelectedMenuItemMessage.ToolProvider);
        }

        [Test]
        public void TestChangeSelectedMenuItemMessage_ChangeSelectedMenuItemMessage_NullToolProvider_21f3b66d7c()
        {
            //Arrange
            IToolProvider toolProvider = null;

            //Act and Assert
            Assert.That(() => new ChangeSelectedMenuItemMessage(toolProvider), Throws.ArgumentNullException);
        }
    }
}
