// Test generated by RoostGPT for test int-test using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using DevToys.Messages;
using NUnit.Framework;

namespace DevToys.Tests
{
    [TestFixture]
    public class NavigateToMarkdownPreviewHtmlMessageTests
    {
        [Test]
        public void TestNavigateToMarkdownPreviewHtmlMessage_NavigateToMarkdownPreviewHtmlMessage_2b1a6dc6ce_Success()
        {
            // Arrange
            string html = "<h1>This is a test</h1>";
            NavigateToMarkdownPreviewHtmlMessage message = new NavigateToMarkdownPreviewHtmlMessage(html);

            // Act
            string actualHtml = message.Html;

            // Assert
            Assert.AreEqual(html, actualHtml);
        }

        [Test]
        public void TestNavigateToMarkdownPreviewHtmlMessage_NavigateToMarkdownPreviewHtmlMessage_2b1a6dc6ce_NullHtml()
        {
            // Arrange
            string html = null;

            // Act
            NavigateToMarkdownPreviewHtmlMessage message = new NavigateToMarkdownPreviewHtmlMessage(html);

            // Assert
            Assert.IsNull(message.Html);
        }
    }
}
