// Test generated by RoostGPT for test int-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System.Diagnostics;

namespace MyNamespace.Tests
{
    [TestFixture]
    public class DebugLoggerTests
    {
        [Test]
        public void TestDebugLogger_Log_MessageIsLoggedInDebugMode()
        {
            // Arrange
            DebugLogger debugLogger = new DebugLogger();
            string message = "Test message";

            // Act
            debugLogger.Log(message);

            // Assert
            // TODO: Verify that the message is logged in the debug output
            // You can use a third-party library like Microsoft.Extensions.Logging.Abstractions for better logging functionality
        }

        [Test]
        public void TestDebugLogger_Log_MessageIsNotLoggedInReleaseMode()
        {
            // Arrange
            DebugLogger debugLogger = new DebugLogger();
            string message = "Test message";

            // Act
            debugLogger.Log(message);

            // Assert
            // TODO: Verify that the message is not logged in the debug output
            // You can use a third-party library like Microsoft.Extensions.Logging.Abstractions for better logging functionality
        }
    }

    public class DebugLogger
    {
        public void Log(string message)
        {
#if DEBUG
            Debug.WriteLine(message);
#endif
        }
    }
}
