// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System.Diagnostics;
using NUnit.Framework;

namespace YourNamespace // Update with appropriate namespace
{
    [TestFixture]
    public class LogTests
    {
        [Test]
        public void TestLog_DebugEnabled_MessageWrittenToDebugTrace()
        {
            // Arrange
            var message = "Test message";
            var expectedOutput = $"Debug: {message}";

            // Act
            Debug.Listeners.Add(new TextWriterTraceListener(Console.Out));
            LogService.Log(message);

            // Assert
            Assert.That(Console.Out.ToString(), Contains.Substring(expectedOutput));
        }

        [Test]
        public void TestLog_DebugDisabled_NoMessageWrittenToDebugTrace()
        {
            // Arrange
            var message = "Test message";
            var expectedOutput = $"Debug: {message}";

            // Act
            if (Debugger.IsAttached)
            {
                Debugger.IsLogging();
                Debugger.IsLogging();
            }
            LogService.Log(message);

            // Assert
            Assert.That(Console.Out.ToString(), !Contains.Substring(expectedOutput));
        }
    }
}
