// Test generated by RoostGPT for test int-test using AI Type Azure Open AI and AI Model roost-gpt

using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace YourNamespace
{
    [TestFixture]
    public class YourTestClass
    {
        [Test]
        public void TestCallAction_Success()
        {
            // Arrange
            var actions = new Dictionary<string, Action>();
            actions.Add("action1", () => Console.WriteLine("Action 1 executed"));

            // Act
            var result = CallAction("action1");

            // Assert
            Assert.IsTrue(result);
        }

        [Test]
        public void TestCallAction_Failure()
        {
            // Arrange
            var actions = new Dictionary<string, Action>();
            actions.Add("action1", () => Console.WriteLine("Action 1 executed"));

            // Act
            var result = CallAction("action2");

            // Assert
            Assert.IsFalse(result);
        }

        public bool CallAction(string name)
        {
            Dictionary<string, Action> actions = null; // TODO: Provide an actual dictionary with actions

            if (actions is not null && actions.ContainsKey(name))
            {
                actions[name]?.Invoke();
                return true;
            }

            return false;
        }
    }
}
