// Test generated by RoostGPT for test unt-test using AI Type Azure Open AI and AI Model roost-gpt

using System;
using Windows.ApplicationModel.Core;
using Windows.Foundation.Metadata;
using Windows.UI;
using Windows.UI.ViewManagement;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Media;
using NUnit.Framework;

namespace YourNamespace
{
    public class YourTestClass
    {
        private YourClass _yourObject;

        [SetUp]
        public void Setup()
        {
            _yourObject = new YourClass();
        }

        [Test]
        public void Test_UpdateProperties_WhenHighContrastSchemeContainsWhite_ShouldSetIsHighContrastToFalseAndCurrentThemeToLight()
        {
            _yourObject.Accessible.HighContrast = true;
            _yourObject.Accessible.HighContrastScheme = "White High Contrast Scheme";

            _yourObject.UpdateProperties();

            Assert.IsFalse(_yourObject.IsHighContrast);
            Assert.AreEqual(ApplicationTheme.Light, _yourObject.CurrentTheme);
        }

        [Test]
        public void Test_UpdateProperties_WhenHighContrastSchemeDoesNotContainWhite_ShouldSetIsHighContrastToAccessibleHighContrastValueAndSetCurrentThemeBasedOnActualTheme()
        {
            _yourObject.Accessible.HighContrast = false;
            _yourObject.Accessible.HighContrastScheme = "Red High Contrast Scheme";
            var content = new FrameworkElement
            {
                ActualTheme = ElementTheme.Dark
            };
            Window.Current.Content = content;

            _yourObject.UpdateProperties();

            Assert.IsFalse(_yourObject.IsHighContrast);
            Assert.AreEqual(ApplicationTheme.Dark, _yourObject.CurrentTheme);
        }
    }
}
